# Generated by Django 3.1.1 on 2020-09-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200906_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pokedex.abilities'),
        ),
    ]
