# Generated by Django 3.1.1 on 2020-09-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20200906_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='debilities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='debilities', to='pokedex.abilities'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='pokemon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='pokedex.abilities'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='laterEvolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='later', to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previousEvolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='pokedex.pokemon'),
        ),
        migrations.DeleteModel(
            name='Weaknesses',
        ),
    ]
