# Generated by Django 3.1.1 on 2020-09-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_auto_20200906_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pokedex.abilities'),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='debilities',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='debilities',
            field=models.ManyToManyField(related_name='debilities', to='pokedex.Type'),
        ),
    ]
