# Generated by Django 3.1.1 on 2020-09-12 00:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_imagepokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepokemon',
            name='publicIdImage',
        ),
        migrations.RemoveField(
            model_name='imagepokemon',
            name='urlImage',
        ),
        migrations.AddField(
            model_name='imagepokemon',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
        ),
    ]
