# Generated by Django 3.1.1 on 2020-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_auto_20200911_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepokemon',
            name='idImage',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='imagepokemon',
            name='urlImage',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
