# Generated by Django 3.1.1 on 2020-09-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_auto_20200911_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepokemon',
            name='idImage',
            field=models.CharField(max_length=250),
        ),
    ]
