# Generated by Django 3.1.1 on 2020-09-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_auto_20200911_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepokemon',
            old_name='idImage',
            new_name='keyImage',
        ),
    ]
