# Generated by Django 3.1.1 on 2020-09-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_remove_imagepokemon_keyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepokemon',
            name='keyImage',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
