# Generated by Django 3.1.1 on 2020-09-12 01:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0013_imagepokemon_keyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepokemon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='file'),
        ),
    ]
